server:
  port: 7004
my:
  greeting: Hello

db:
  connection: connection
  host: host
  port: port

management:
  endpoints:
   web:
    exposure:
     include: "*"
spring:


  config:
    import: optional:configserver:http://localhost:7005


